- name: Start container on webhook event
  hosts: localhost
  gather_facts: false
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: launch playbook when start signal received
      condition: event.payload.command == "let's start"
      action:
        run_playbook:
          name: start_container.yml
          # inventory: /home/ec2-user/inventory.yml