- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - webhook:
        port: "{{ port | default(2345) }}"
        host: 0.0.0.0
  rules:
    # - name: print event
    #   condition: true
    #   action:
    #     print_event:
    #       pretty: true
    # - name: debug
    #   condition: true
    #   action:
    #     debug:
    #       msg: "event.payload.result.status = {{ event.payload.result.status }}"
    - name: restart process
      condition: event.payload.result.status == "down"
      action:
        run_playbook:
          name: demo_playbook.yml