---
# This rulebook is for demo purposes only
# This webhook listens on port 2345 by default,
# you can override it by passing in an variable
# called port. If you have other webhook sources
# running on the default port 2345 you might see
# port conflicts.
# It logs every event received so it should work
# with any vendors payload.
# It doesn't use authentication to keep things simple
#
- name: Webhook demo prints all incoming events
  hosts: all
  sources:
    - webhook:
        port: "{{ port | default(2345) }}"
        host: 0.0.0.0
  rules:
    - name: Webhook rule
      condition: true
      action:
        print_event:
          pretty: true
